_target_: model.lb_single_seq_decoder_alfred.Model 
model_conf:
  env_name: alfred
  pred_done: True
  pred_progress: False
  binary_pos_weight: null
  data_dir: /misery/anthony/alfred_orig_lmdb_2.1.0
  stochastic: False
  continuous_actions: False
  state_dim: 256
  action_dim: 2 # one for action and another for target obj
  alpha_lr: 1e-4
  weight_decay: 0.99
  log_std_min: -20
  log_std_max: 2

  # loss weighting
  language_only:
    pred_loss_weight: 1.0

  behavior_only:
    action_pred_loss_weight: 1.0
    target_pred_loss_weight: 1.0
    entropy_loss_weight: 1.0
    log_alpha_loss_weight: 1.0

  aux_pred_loss_weight: 1.0

  paired:
    lang_pred_loss_weight: 1.0
    action_pred_loss_weight: 1.0
    target_pred_loss_weight: 1.0
    entropy_loss_weight: 1.0
    log_alpha_loss_weight: 1.0

  state_encoder:  
    enc_method: mlp
    input_type: resnet_feats
    enc_dim: 256