sampler:
  _target_: eval.rollout.Rollout
  config:
    max_episode_len: 280
    save_video: False
    num_samples: 10
    prompt: null
    video_prefix: null
    save_dir: /data/anthony/gpt_transformer/logs/
    exp_name: test
    self_prompting: False 
    model_target: model.lb_single_seq_decoder
    use_model_generate: True
    reset_from_demonstration_state: False
    predict_lang: False
    data_dir: /data/anthony/gpt_policy/data/kitchen

env:
  _target_: envs.kitchen.KitchenEnv
  config:
    # name: kitchen-mixed-v0  # kitchen-all-tasks-v0
    # name: kitchen-all-tasks-v0
    name: kitchen-mlsh-v0
    unwrap_time: True
    reward_norm: 1.
    punish_reward: -100
    screen_height: 256
    screen_width: 256