_target_: pytorch_lightning.trainer.trainer.Trainer
logger: 
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: /data/anthony/gpt_transformer/logs
    name: transformerBC_init_w_pretrained_gpt2
  - _target_: pytorch_lightning.loggers.WandbLogger
    save_dir: ${logger[0].save_dir}
    name: ${logger[0].name}
    entity: clvr
    project: gpt_lang_transformer

# checkpoint_callback: true
enable_checkpointing: true
callbacks: 
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${logger[0].save_dir}/${logger[0].name}
    save_top_k: 5         # save the last-k checkpoints
    monitor: step 
    mode: max
    filename: ${logger[0].name}-{epoch:02d}-{step}

default_root_dir: null
gradient_clip_val: null
gradient_clip_algorithm: null
# process_position: 0
num_nodes: 1
num_processes: null
devices: 1
gpus: 1
auto_select_gpus: false
tpu_cores: null
ipus: null
# log_gpu_memory: null
# progress_bar_refresh_rate: null
enable_progress_bar: true
overfit_batches: 0.0
track_grad_norm: -1
check_val_every_n_epoch: 1
fast_dev_run: false
accumulate_grad_batches: null
max_epochs: 100
min_epochs: null
max_steps: -1
min_steps: null
max_time: null
limit_train_batches: null
limit_val_batches: null
limit_test_batches: null
limit_predict_batches: null
val_check_interval: null
# flush_logs_every_n_steps: null
log_every_n_steps: 50
accelerator: auto
strategy: null
sync_batchnorm: false
precision: 32
enable_model_summary: true
# weights_summary: top
weights_save_path: null
num_sanity_val_steps: 2
resume_from_checkpoint: null
profiler: null
benchmark: null
deterministic: null
reload_dataloaders_every_n_epochs: 0
auto_lr_find: false
replace_sampler_ddp: true
detect_anomaly: false
auto_scale_batch_size: false
# prepare_data_per_node: null
plugins: null
amp_backend: native
amp_level: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
# stochastic_weight_avg: false
# terminate_on_nan: null
# ckpt_path: null