output_dir: /misery/anthony/eval_results
subgoals: False
device: cuda
fast_epoch: true
num_workers: 0
object_predictor: /misery/anthony/pretrained/maskrcnn_model.pth
debug: True 

sampler:
  _target_: evals.rollout.ALFREDRollout
  config:
    # max_episode_len: 280 
    save_video: False
    save_dir: /data/anthony/gpt_transformer/logs/
    data_dir: /misery/anthony/alfred_orig_lmdb_2.1.0
    exp_name: test
    model_target: model.lb_single_seq_decoder_alfred

    predict_lang: False

    # eval stuff
    multistream_inference: True

    # support_threshold: 5
    fixed_lang_only_prior_weight: 0.0
    fixed_paired_lang_prior_weight: 1.0

    # fixed_lang_only_prior_weight: 1.0
    # fixed_paired_lang_prior_weight: 0.0
    
    fixed_beh_only_prior_weight: 0.0
    fixed_paired_beh_prior_weight: 1.0

    teacher_forcing: False
    
    debug: ${debug}

    dataset_args:
      data_dir: /misery/anthony/alfred_orig_lmdb_2.1.0
      ET_ROOT: /data/anthony/ET
      decoder_model_cls: gpt2
      load_lang: True
      chunk_size: 512
      partition: train
      load_frac_done: False
      debug: ${debug}

    object_predictor_args: 
      device: cuda
      object_predictor: /misery/anthony/pretrained/maskrcnn_model.pth

    # prompt: Pick up the soap from the cart. stop

    target_return: 10
    return_conditioned: False

env:
  _target_: envs.alfred_env.ALFREDEnv
  config:
    name: alfred-v0
    unwrap_time: True
    reward_norm: 1.
    punish_reward: -100
    screen_height: 256
    screen_width: 256
    x_display: 0
    smooth_nav: False
    max_fails: 10
    debug: ${debug}