logger: 
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: /data/anthony/gpt_transformer/logs
    name: behavior_only_v2
  - _target_: pytorch_lightning.loggers.WandbLogger
    save_dir: ${logger[0].save_dir}
    name: ${logger[0].name}
    entity: clvr
    project: gpt_lang_transformer


# resume_from_checkpoint: /data/anthony/gpt_transformer/logs/behavior_only/behavior_only-epoch=99-step=54000.ckpt
# max_epochs: 100