sampler:
  _target_: eval.rollout.Rollout
  config:
    max_episode_len: 280
    save_video: True
    num_samples: 2
    prompt: open the sliding cabinet
    video_prefix: prompting_sliding_cabinet

env:
  _target_: envs.kitchen.KitchenEnv
  config:
    name: kitchen-mixed-v0  # kitchen-all-tasks-v0