class_path: data.kitchen.LanguageBehaviorDataModule
init_args:
  data_conf: 
    env_name: kitchen-mixed-v0
    split:
      train: 0.8
      val: 0.2
    batch_size: 4
    data_dir: /data/anthony/kitchen/single_ann
    state_dim: 60
    action_dim: 9
    modalities:
      - paired
      - language

    dataset_cls: # config for the dataset
      _target_: data.kitchen.SingleSequenceKitchenDataset
      hparams:
        load_frac_done: True
        load_lang: True
        decoder_model_cls: gpt2
        subseq_len: 10
        data_dir: ${init_args.data_conf.data_dir} 
        annotation_file: annotations.json
        add_lang_before_state: False
        discretize_actions: False
        num_bins: 256
        prepend_lang: True
        chunk_size: 512
      
    paired_dataset_cls: ${init_args.data_conf.dataset_cls}

    language_dataset_cls: 
      _target_: data.language.LanguageDataset
      hparams: 
        data_dir: ${init_args.data_conf.data_dir} 
        vocab_file: kitchen.vocab
        mapping_file: text_to_emb.pkl
        annotation_file: annotations.json
        language_skills_file: skills_small.txt
        chunk_size: ${init_args.data_conf.dataset_cls.hparams.chunk_size}
        decoder_model_cls: ${init_args.data_conf.dataset_cls.hparams.decoder_model_cls}

    dataloader_cls:
      _target_: data.sampler.RepeatedDataLoader
      n_repeat: 10
      num_workers: 4
      batch_size: 8