sampler:
  _target_: eval.rollout.Rollout
  config:
    max_episode_len: 280
    save_video: False
    save_dir: ${trainer.logger[0].init_args.save_dir}/${trainer.logger[0].init_args.name}
    num_samples: 2
    prompt: move the kettle

env:
  _target_: envs.kitchen.KitchenEnv
  config:
    name: kitchen-mixed-v0  # kitchen-all-tasks-v0