sampler:
  _target_: eval.rollout.Rollout
  config:
    max_episode_len: 280
    save_video: False
    num_samples: 50
    # prompt: open the sliding cabinet
    # video_prefix: prompting_sliding_cabinet
    prompt: null
    video_prefix: transformerBC
    save_dir: /data/anthony/gpt_transformer/logs
    exp_name: transformerBC

env:
  _target_: envs.kitchen.KitchenEnv
  config:
    name: kitchen-all-tasks-v0  # kitchen-all-tasks-v0