_target_: data.language_behavior.ALFREDLanguageBehaviorDataModule
data_conf: 
  env_name: alfred
  split:
    train: 0.8
    val: 0.2
  batch_size: 4
  data_dir: /misery/anthony/alfred_orig_lmdb_2.1.0
  seed: 42
  modalities:
    - behavior
  
  behavior_dataset_cls: 
    _target_: data.alfred.ALFREDTrajectoryDataset
    hparams: 
      load_frac_done: True
      load_lang: False
      decoder_model_cls: gpt2
      data_dir: ${data_conf.data_dir} 
      partition: train
      discretize_actions: False
      num_bins: 256
      chunk_size: 512
      return_conditioned: True 
      input_format: v1      

  dataloader_cls:
    _target_: data.sampler.RepeatedDataLoader
    n_repeat: 5
    num_workers: 4
    batch_size: 6